all: j

j: j1 j2 j3 j4 j5

r: r1 r2 r3 r4 r5


j1:
	make -C 1/ j

r1:
	make -C 1/ r

tj1:
	make -C 1/ tj

tr1:
	make -C 1/ tr

tjp1:
	make -C 1/ tjp

trp1:
	make -C 1/ trp

rer1:
	make -C 1/ rer

rej1:
	make -C 1/ rej


j2:
	make -C 2/ j

r2:
	make -C 2/ r

tj2:
	make -C 2/ tj

tr2:
	make -C 2/ tr

rer2:
	make -C 2/ rer

rej2:
	make -C 2/ rej


j3:
	make -C 3/ j

r3:
	make -C 3/ r

tj3:
	make -C 3/ tj

tr3:
	make -C 3/ tr

rer3:
	make -C 3/ rer

rej3:
	make -C 3/ rej


j4:
	make -C 4/ j

r4:
	make -C 4/ r

tj4:
	make -C 4/ tj

tr4:
	make -C 4/ tr

rer4:
	make -C 4/ rer

rej4:
	make -C 4/ rej


j5:
	make -C 5/ j

r5:
	make -C 5/ r

tj5:
	make -C 5/ tj

tr5:
	make -C 5/ tr

rer5:
	make -C 5/ rer

rej5:
	make -C 5/ rej
