all: j

j: j1 j2 j3 j4 j5

r: r1 r2 r3 r4 r5


j1:
	make -C 1/ j

r1:
	make -C 1/ r

tj1:
	make -C 1/ tj

tr1:
	make -C 1/ tr

rep1:
	make -C 1/ rep


j2:
	make -C 2/ j

r2:
	make -C 2/ r

tj2:
	make -C 2/ tj

tr2:
	make -C 2/ tr

rep2:
	make -C 2/ rep


j3:
	make -C 3/ j

r3:
	make -C 3/ r

tj3:
	make -C 3/ tj

tr3:
	make -C 3/ tr

rep3:
	make -C 3/ rep


j4:
	make -C 4/ j

r4:
	make -C 4/ r

tj4:
	make -C 4/ tj

tr4:
	make -C 4/ tr

rep4:
	make -C 4/ rep


j5:
	make -C 5/ j

r5:
	make -C 5/ r

tj5:
	make -C 5/ tj

tr5:
	make -C 5/ tr

rep5:
	make -C 5/ rep
