all: rej

rej: rej1 rej2 rej3 rej4 rej5
rer: rer1 rer2 rer3 rer4 rer5
tj: tj1 tj2 tj3 tj4 tj5
tr: tr1 tr2 tr3 tr4 tr5
tjp: tjp1 tjp2 tjp3 tjp4 tjp5
trp: trp1 trp2 trp3 trp4 trp5
j: j1 j2 j3 j4 j5
r: r1 r2 r3 r4 r5


j1:
	make -C 1/ j

r1:
	make -C 1/ r

tj1:
	make -C 1/ tj

tr1:
	make -C 1/ tr

tjp1:
	make -C 1/ tjp

trp1:
	make -C 1/ trp

rer1:
	make -C 1/ rer

rej1:
	make -C 1/ rej


j2:
	make -C 2/ j

r2:
	make -C 2/ r

tj2:
	make -C 2/ tj

tr2:
	make -C 2/ tr

tjp2:
	make -C 2/ tjp

trp2:
	make -C 2/ trp

rer2:
	make -C 2/ rer

rej2:
	make -C 2/ rej


j3:
	make -C 3/ j

r3:
	make -C 3/ r

tj3:
	make -C 3/ tj

tr3:
	make -C 3/ tr

tjp3:
	make -C 3/ tjp

trp3:
	make -C 3/ trp

rer3:
	make -C 3/ rer

rej3:
	make -C 3/ rej


j4:
	make -C 4/ j

r4:
	make -C 4/ r

tj4:
	make -C 4/ tj

tr4:
	make -C 4/ tr

tjp4:
	make -C 4/ tjp

trp4:
	make -C 4/ trp

rer4:
	make -C 4/ rer

rej4:
	make -C 4/ rej


j5:
	make -C 5/ j

r5:
	make -C 5/ r

tj5:
	make -C 5/ tj

tr5:
	make -C 5/ tr

tjp5:
	make -C 5/ tjp

trp5:
	make -C 5/ trp

rer5:
	make -C 5/ rer

rej5:
	make -C 5/ rej


jo:
	make -C ocr/ j

ro:
	make -C ocr/ r

tjo:
	make -C ocr/ tj

tro:
	make -C ocr/ tr

tjpo:
	make -C ocr/ tjp

trpo:
	make -C ocr/ trp

rero:
	make -C ocr/ rer

rejo:
	make -C ocr/ rej
